In [22]:
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv('../data/AdSmartABdata.csv')

In [25]:
df = df.query('yes==1 or no==1')

In [27]:
columns = df.columns
print(columns)

Index(['auction_id', 'experiment', 'date', 'hour', 'device_make',
       'platform_os', 'browser', 'yes', 'no'],
      dtype='object')

In [33]:
os_cols = set(columns) - set(['browser'])
print(os_cols)

{'date', 'hour', 'yes', 'device_make', 'auction_id', 'platform_os', 'no', 'experiment'}

In [34]:
browser_cols = set(columns) - set(['platform_os'])
print(browser_cols)

{'date', 'hour', 'yes', 'device_make', 'auction_id', 'browser', 'no', 'experiment'}

In [36]:
df_browser = df[browser_cols]
df_browser

,date,hour,yes,device_make,auction_id,browser,no,experiment
2,2020-07-05,2,0,E5823,0016d14a-ae18-4a02-a204-6ba53b52f2ed,Chrome Mobile WebView,1,exposed
16,2020-07-04,16,1,Generic Smartphone,008aafdf-deef-4482-8fec-d98e3da054da,Chrome Mobile,0,exposed
20,2020-07-06,8,0,Generic Smartphone,00a1384a-5118-4d1b-925b-6cdada50318d,Chrome Mobile,1,exposed
23,2020-07-08,4,1,Samsung SM-A202F,00b6fadb-10bd-49e3-a778-290da82f7a8d,Facebook,0,control
27,2020-07-03,15,0,Generic Smartphone,00ebf4a8-060f-4b99-93ac-c62724399483,Chrome Mobile,1,control
...,...,...,...,...,...,...,...,...
8059,2020-07-05,21,1,Generic Smartphone,ffa08ff9-a132-4051-aef5-01a9c79367bc,Chrome Mobile,0,exposed
8063,2020-07-04,1,1,Generic Smartphone,ffb176df-ecd2-45d3-b05f-05b173a093a7,Chrome Mobile,0,exposed
8064,2020-07-09,7,0,Generic Smartphone,ffb79718-6f25-4896-b6b3-e58b80a6e147,Chrome Mobile,1,control
8069,2020-07-10,16,0,Generic Smartphone,ffca1153-c182-4f32-9e90-2a6008417497,Chrome Mobile,1,control
8071,2020-07-03,4,0,Generic Smartphone,ffdfdc09-48c7-4bfb-80f8-ec1eb633602b,Chrome Mobile,1,exposed

In [38]:
df_os = df[os_cols]
df_os

,date,hour,yes,device_make,auction_id,platform_os,no,experiment
2,2020-07-05,2,0,E5823,0016d14a-ae18-4a02-a204-6ba53b52f2ed,6,1,exposed
16,2020-07-04,16,1,Generic Smartphone,008aafdf-deef-4482-8fec-d98e3da054da,6,0,exposed
20,2020-07-06,8,0,Generic Smartphone,00a1384a-5118-4d1b-925b-6cdada50318d,6,1,exposed
23,2020-07-08,4,1,Samsung SM-A202F,00b6fadb-10bd-49e3-a778-290da82f7a8d,6,0,control
27,2020-07-03,15,0,Generic Smartphone,00ebf4a8-060f-4b99-93ac-c62724399483,6,1,control
...,...,...,...,...,...,...,...,...
8059,2020-07-05,21,1,Generic Smartphone,ffa08ff9-a132-4051-aef5-01a9c79367bc,6,0,exposed
8063,2020-07-04,1,1,Generic Smartphone,ffb176df-ecd2-45d3-b05f-05b173a093a7,6,0,exposed
8064,2020-07-09,7,0,Generic Smartphone,ffb79718-6f25-4896-b6b3-e58b80a6e147,6,1,control
8069,2020-07-10,16,0,Generic Smartphone,ffca1153-c182-4f32-9e90-2a6008417497,6,1,control
8071,2020-07-03,4,0,Generic Smartphone,ffdfdc09-48c7-4bfb-80f8-ec1eb633602b,6,1,exposed