# Data Preparation Form ML Modeling

In [2]:
import pandas as pd
import seaborn as sns
import os, sys

In [3]:

path_parent = os.path.dirname(os.getcwd())
os.chdir(path_parent)
sys.path.insert(0, path_parent+'/notebooks')
sys.path.insert(0, path_parent+'/data')

In [6]:
df = pd.read_csv('data/AdSmartABdata.csv')

In [7]:
df.head(10)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1
3,00187412-2932-4542-a8ef-3633901c98d9,control,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0
4,001a7785-d3fe-4e11-a344-c8735acacc2c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0
5,0027ce48-d3c6-4935-bb12-dfb5d5627857,control,2020-07-03,15,Samsung SM-G960F,6,Facebook,0,0
6,002e308b-1a07-49d6-8560-0fbcdcd71e4b,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0
7,00393fb9-ca32-40c0-bfcb-1bd83f319820,control,2020-07-09,5,Samsung SM-G973F,6,Facebook,0,0
8,004940f5-c642-417a-8fd2-c8e5d989f358,exposed,2020-07-04,0,Generic Smartphone,6,Chrome Mobile WebView,0,0
9,004c4cc9-f2ca-4df7-adc9-3d0c3c4f0342,control,2020-07-05,14,Generic Smartphone,6,Chrome Mobile,0,0

In [29]:
yeses = list(df[["yes", "no"]].values[:,0])
nos = list(df[["yes", "no"]].values[:,1])

In [30]:
response = []
for i in range(len(yeses)):
    if(yeses[i] == 1):
        response.append(1)
    elif (nos[i] == 1):
        response.append(0)
    else:
        response.append(2)

In [31]:
len(response)

8077

In [33]:
df['response'] = response
df.head(100)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,response
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0,2
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0,2
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1,0
3,00187412-2932-4542-a8ef-3633901c98d9,control,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0,2
4,001a7785-d3fe-4e11-a344-c8735acacc2c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0,2
...,...,...,...,...,...,...,...,...,...,...
95,030f8197-4daa-4584-a43a-a5805d6947e4,exposed,2020-07-08,20,Generic Smartphone,6,Chrome Mobile,0,1,0
96,0315f5f3-d286-4d23-abbc-1c7b8401991f,control,2020-07-07,22,Generic Smartphone,6,Chrome Mobile,0,0,2
97,0320f9a0-7e0a-4c0d-a553-66c75d71a2ea,exposed,2020-07-08,19,Generic Smartphone,6,Chrome Mobile,0,0,2
98,03244a64-9192-40fc-9bd7-7edd1bd9643a,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0,2
99,0332792f-0de9-4902-9d08-06033c3d8371,control,2020-07-06,2,Samsung SM-J600FN,6,Chrome Mobile WebView,0,1,0

In [34]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [35]:
le.fit(df['experiment'])

LabelEncoder()

In [36]:
le.classes_

array(['control', 'exposed'], dtype=object)

In [37]:
ex = le.transform(df['experiment'])
ex

array([1, 1, 1, ..., 0, 1, 0])

In [38]:
df['experiment'] = ex

In [39]:
df.head(100)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,response
0,0008ef63-77a7-448b-bd1e-075f42c55e39,1,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0,2
1,000eabc5-17ce-4137-8efe-44734d914446,1,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0,2
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,1,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1,0
3,00187412-2932-4542-a8ef-3633901c98d9,0,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0,2
4,001a7785-d3fe-4e11-a344-c8735acacc2c,0,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0,2
...,...,...,...,...,...,...,...,...,...,...
95,030f8197-4daa-4584-a43a-a5805d6947e4,1,2020-07-08,20,Generic Smartphone,6,Chrome Mobile,0,1,0
96,0315f5f3-d286-4d23-abbc-1c7b8401991f,0,2020-07-07,22,Generic Smartphone,6,Chrome Mobile,0,0,2
97,0320f9a0-7e0a-4c0d-a553-66c75d71a2ea,1,2020-07-08,19,Generic Smartphone,6,Chrome Mobile,0,0,2
98,03244a64-9192-40fc-9bd7-7edd1bd9643a,0,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0,2
99,0332792f-0de9-4902-9d08-06033c3d8371,0,2020-07-06,2,Samsung SM-J600FN,6,Chrome Mobile WebView,0,1,0

In [40]:
le.fit(df['device_make'])
le.classes_
df['device_make'] = le.transform(df['device_make'])

In [41]:
df.head(100)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,response
0,0008ef63-77a7-448b-bd1e-075f42c55e39,1,2020-07-10,8,46,6,Chrome Mobile,0,0,2
1,000eabc5-17ce-4137-8efe-44734d914446,1,2020-07-07,10,46,6,Chrome Mobile,0,0,2
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,1,2020-07-05,2,29,6,Chrome Mobile WebView,0,1,0
3,00187412-2932-4542-a8ef-3633901c98d9,0,2020-07-03,15,137,6,Facebook,0,0,2
4,001a7785-d3fe-4e11-a344-c8735acacc2c,0,2020-07-03,15,46,6,Chrome Mobile,0,0,2
...,...,...,...,...,...,...,...,...,...,...
95,030f8197-4daa-4584-a43a-a5805d6947e4,1,2020-07-08,20,46,6,Chrome Mobile,0,1,0
96,0315f5f3-d286-4d23-abbc-1c7b8401991f,0,2020-07-07,22,46,6,Chrome Mobile,0,0,2
97,0320f9a0-7e0a-4c0d-a553-66c75d71a2ea,1,2020-07-08,19,46,6,Chrome Mobile,0,0,2
98,03244a64-9192-40fc-9bd7-7edd1bd9643a,0,2020-07-03,15,46,6,Chrome Mobile,0,0,2
99,0332792f-0de9-4902-9d08-06033c3d8371,0,2020-07-06,2,204,6,Chrome Mobile WebView,0,1,0

In [42]:
le.fit(df['platform_os'])
df['platform_os'] = le.transform(df['platform_os'])

le.classes_

array([5, 6, 7], dtype=int64)

In [43]:
df.head(100)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,response
0,0008ef63-77a7-448b-bd1e-075f42c55e39,1,2020-07-10,8,46,1,Chrome Mobile,0,0,2
1,000eabc5-17ce-4137-8efe-44734d914446,1,2020-07-07,10,46,1,Chrome Mobile,0,0,2
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,1,2020-07-05,2,29,1,Chrome Mobile WebView,0,1,0
3,00187412-2932-4542-a8ef-3633901c98d9,0,2020-07-03,15,137,1,Facebook,0,0,2
4,001a7785-d3fe-4e11-a344-c8735acacc2c,0,2020-07-03,15,46,1,Chrome Mobile,0,0,2
...,...,...,...,...,...,...,...,...,...,...
95,030f8197-4daa-4584-a43a-a5805d6947e4,1,2020-07-08,20,46,1,Chrome Mobile,0,1,0
96,0315f5f3-d286-4d23-abbc-1c7b8401991f,0,2020-07-07,22,46,1,Chrome Mobile,0,0,2
97,0320f9a0-7e0a-4c0d-a553-66c75d71a2ea,1,2020-07-08,19,46,1,Chrome Mobile,0,0,2
98,03244a64-9192-40fc-9bd7-7edd1bd9643a,0,2020-07-03,15,46,1,Chrome Mobile,0,0,2
99,0332792f-0de9-4902-9d08-06033c3d8371,0,2020-07-06,2,204,1,Chrome Mobile WebView,0,1,0

In [44]:
le.fit(df['browser'])
df['browser'] = le.transform(df['browser'])

le.classes_

array(['Android', 'Chrome', 'Chrome Mobile', 'Chrome Mobile WebView',
       'Chrome Mobile iOS', 'Edge Mobile', 'Facebook', 'Firefox Mobile',
       'Mobile Safari', 'Mobile Safari UI/WKWebView', 'Opera Mini',
       'Opera Mobile', 'Pinterest', 'Puffin', 'Samsung Internet'],
      dtype=object)

In [45]:
df.head(100)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,response
0,0008ef63-77a7-448b-bd1e-075f42c55e39,1,2020-07-10,8,46,1,2,0,0,2
1,000eabc5-17ce-4137-8efe-44734d914446,1,2020-07-07,10,46,1,2,0,0,2
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,1,2020-07-05,2,29,1,3,0,1,0
3,00187412-2932-4542-a8ef-3633901c98d9,0,2020-07-03,15,137,1,6,0,0,2
4,001a7785-d3fe-4e11-a344-c8735acacc2c,0,2020-07-03,15,46,1,2,0,0,2
...,...,...,...,...,...,...,...,...,...,...
95,030f8197-4daa-4584-a43a-a5805d6947e4,1,2020-07-08,20,46,1,2,0,1,0
96,0315f5f3-d286-4d23-abbc-1c7b8401991f,0,2020-07-07,22,46,1,2,0,0,2
97,0320f9a0-7e0a-4c0d-a553-66c75d71a2ea,1,2020-07-08,19,46,1,2,0,0,2
98,03244a64-9192-40fc-9bd7-7edd1bd9643a,0,2020-07-03,15,46,1,2,0,0,2
99,0332792f-0de9-4902-9d08-06033c3d8371,0,2020-07-06,2,204,1,3,0,1,0

### Split the Data by browser and platform_os
> and version each split as a new version of the data in dvc.

In [46]:
by_browser =  df.drop(columns=['platform_os'])

In [47]:
by_browser.to_csv('data/AdSmartABdata.csv')

In [48]:
by_os =  df.drop(columns=['browser'])

In [49]:
by_os.to_csv('data/AdSmartABdata.csv')